'use client'

import { useEffect, useState } from 'react'

type Player={uuid:string;username:string;rank_name:string|null;rank_prefix:string|null;rank_suffix:string|null;online:boolean;playtime_minutes:number;coins:number;kills:number;deaths:number;last_seen_at:string|null}
export function AdminPlayerPanel(){
 const [items,setItems]=useState<Player[]>([]),[query,setQuery]=useState(''),[editing,setEditing]=useState<Player|null>(null),[rank,setRank]=useState(''),[prefix,setPrefix]=useState(''),[suffix,setSuffix]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 async function load(q=''){const r=await fetch('/api/admin/players?search='+encodeURIComponent(q),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'خطا');setItems(d.players||[])}
 useEffect(()=>{load().catch(e=>setNotice(e.message))},[])
 async function search(e:React.FormEvent){e.preventDefault();load(query).catch(e=>setNotice(e.message))}
 function edit(p:Player){setEditing(p);setRank(p.rank_name||'');setPrefix(p.rank_prefix||'');setSuffix(p.rank_suffix||'');setNotice('')}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{const r=await fetch('/api/admin/players',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({uuid:editing.uuid,rank_name:rank,rank_prefix:prefix,rank_suffix:suffix})});const d=await r.json();if(!r.ok)throw Error(d.error||'ذخیره نشد');setNotice('اطلاعات بازیکن ذخیره شد.');await load(query)}catch(e){setNotice(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}}
 return <div><form className="admin-player-search" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجوی نام بازیکن…" /><button className="btn btn-primary" type="submit">جستجو</button></form><div className="table-wrap"><table><thead><tr><th>بازیکن</th><th>رنک</th><th>وضعیت</th><th>آخرین حضور</th><th>عملیات</th></tr></thead><tbody>{items.map(p=><tr key={p.uuid}><td><a className="text-link ltr" href={'/player/'+encodeURIComponent(p.username)}>{p.username}</a><small className="admin-player-uuid">{p.uuid}</small></td><td>{p.rank_name||'—'}</td><td>{p.online?'آنلاین':'آفلاین'}</td><td>{p.last_seen_at||'—'}</td><td><button className="btn btn-quiet btn-small" onClick={()=>edit(p)}>مدیریت</button></td></tr>)}</tbody></table></div>{!items.length&&<p className="empty">بازیکنی پیدا نشد.</p>}{editing&&<div className="admin-player-editor"><div className="admin-player-editor-head"><h3>مدیریت {editing.username}</h3><button className="btn btn-quiet btn-small" onClick={()=>setEditing(null)}>بستن</button></div><p className="muted">UUID: <span className="ltr">{editing.uuid}</span></p><div className="admin-form-grid"><div className="field"><label>نام رنک</label><input value={rank} onChange={e=>setRank(e.target.value)} maxLength={64}/></div><div className="field"><label>Prefix رنک</label><input dir="ltr" value={prefix} onChange={e=>setPrefix(e.target.value)} maxLength={64}/></div><div className="field"><label>Suffix رنک</label><input dir="ltr" value={suffix} onChange={e=>setSuffix(e.target.value)} maxLength={64}/></div></div><div className="admin-player-stats"><span>سکه: {editing.coins}</span><span>کشته: {editing.kills}</span><span>مرگ: {editing.deaths}</span><span>زمان بازی: {editing.playtime_minutes} دقیقه</span></div><button className="btn btn-primary" disabled={busy} onClick={save}>{busy?'در حال ذخیره…':'ذخیره تغییرات'}</button>{notice&&<div className="notice">{notice}</div>}</div>}</div>
}