name: KootletLandSync
version: 1.1.0
main: ir.kootletland.sync.KootletLandSync
api-version: '1.21'
depend:
  - LuckPerms
description: Syncs Minecraft player data and LuckPerms ranks to KootletLand.
authors:
  - TheROMZ52
commands:
  kootletlandsync:
    description: KootletLandSync administration command
    usage: /kootletlandsync reload
    permission: kootletlandsync.reload
permissions:
  kootletlandsync.reload:
    description: Allows reloading KootletLandSync
    default: op
